FROM node:8-alpine
WORKDIR /usr/src/app/
USER root
COPY package.json ./
RUN npm install --production
RUN npm install pm2 -g 
COPY ./ ./
RUN npm run build && \
    du -hsc && \
    ls && \
    chmod 777 run.sh
CMD ["run.sh"]



