FROM node:8-alpine
WORKDIR /usr/src/app/
USER root
COPY package.json ./
RUN npm install --production
RUN yarn global add pm2
COPY ./ ./
RUN npm run build
RUN chmod 777 ./run.sh
EXPOSE 8088
CMD ["./run.sh"]

