FROM node:8-alpine
WORKDIR /usr/src/app/
USER root
COPY package.json ./
RUN npm install --silent --no-cache --registry=https://registry.npm.taobao.org
COPY ./ ./
RUN npm run build && \
    du -hsc && \
    ls && \
    chmod 777 run.sh
EXPOSE 80

# CMD ["sh", "-c", "sh run.sh"]
CMD ["npm", "run", "start"]



