version: '3.5'

services:
  docker-nuxt_build:
    build: ../
    container_name: 'docker-nuxt_build'
    image: docker-nuxt_build:v1
    volumes:
      - dists:/usr/src/app/dists
    ports:
      - 8088:8088

  # docker-nuxt_web:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   container_name: 'docker-nuxt_web'
  #   restart: unless-stopped
  #   volumes:
  #     - dists:/usr/share/nginx/html:ro
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  dists:
